import Hero from "@/components/hero";

import Salvation from "@/components/salvation";
import Sermons from "@/components/sermons";
import Services from "@/components/services";
import VisionMission from "@/components/visionMission";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>RCCG The Envoys Center</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-[6em]">
        <Hero />
        <div className="px-4 w-full max-w-[92em] m-auto">
          <Services />
        </div>
        <div className="px-4 m-auto">
          <VisionMission />
        </div>
        {/* <div className="px-4 mx-auto w-full">
          <Sermons />
        </div> */}
        {/* <div className="px-4 mx-auto mb-10">
          <Salvation />
        </div> */}
      </main>
    </>
  );
}
